contract:
  abi:
  - inputs: []
    name: constructor
    stateMutability: nonpayable
    type: constructor
  - anonymous: false
    inputs:
    - indexed: false
      internalType: string
      name: workerKey
      type: string
    - indexed: false
      internalType: string
      name: cmd
      type: string
    name: commandAdded
    type: event
  - anonymous: false
    inputs:
    - indexed: false
      internalType: string
      name: workerKey
      type: string
    name: joinRequest
    type: event
  - inputs:
    - internalType: string
      name: workerKey
      type: string
    - internalType: string
      name: cmd
      type: string
    name: addCommand
    outputs: []
    stateMutability: nonpayable
    type: function
  - inputs:
    - internalType: string
      name: workerKey
      type: string
    name: addWorker
    outputs: []
    stateMutability: nonpayable
    type: function
  - inputs:
    - internalType: string
      name: workerKey
      type: string
    name: join
    outputs: []
    stateMutability: nonpayable
    type: function
  - inputs: []
    name: owner
    outputs:
    - internalType: address
      name: ''
      type: address
    stateMutability: view
    type: function
  - inputs:
    - internalType: uint256
      name: ''
      type: uint256
    name: workers
    outputs:
    - internalType: string
      name: key
      type: string
    stateMutability: view
    type: function
  address: '0x35ba6d71cb48723eB184EDD87EFcAb2ddC19f1FA'
